# Generated by Django 4.2.4 on 2023-11-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classId', models.AutoField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=255)),
                ('classDescription', models.TextField()),
            ],
        ),
    ]
